### ISSUE TITLE
restrict sshd config

### ISSUE THREAD

**Issue by mattcobb** [spacelift-io/spacelift-worker-image#30]
We recently installed the spacelift workers at Lightstep.  Our security scanner (Wiz) recommends that the ssh on these be restricted as described below:

Edit to ssh configuration file, example path - /etc/ssh/sshd_config
Under this file ensure that:
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin prohibit-password

Please consider making these changes to your container image

**Comment by peterdeme** [comment]
Assuming this is fixed now.
